### PR TITLE
Update Telechargement_et_installation.md: : First draft for complete download & install instructions in French. 

### PR DESCRIPTION
**Pull request by mlep**
Update: First draft for complete download & install instructions in French.

### CODE REVIEW

**Comment by mlep** [comment]
You confirm all information?
(I am surprised I got it right...)

**Comment by tcitworld** [comment]
Didn't look fully carefully, but I trust you. ;-)

**Comment by tcitworld** [comment]
Will change later if needed.

**Comment by mlep** [comment]
OK!

**Pull request merged**
