### PR TITLE
Added iOS Chapter in Save your first article

### PR DESCRIPTION
**Pull request by kevmeyer**

### CODE REVIEW

**Comment by nicosomb** [comment]
Thank you. 
This will be online when this build will be OK https://travis-ci.org/wallabag/documentation/builds/47799036

**Comment by nicosomb** [comment]
@kevmeyer What is your email address please?

**Comment by tcitworld** [comment]
It's in the conversations from wallabag-admins.

**Comment by tcitworld** [comment]
Sent by email.

**Pull request merged**
