### PR TITLE
[WIP] Migration to ReadTheDocs

### PR DESCRIPTION
**Pull request by nicosomb**
For next wallabag version, we'll publish our documentation on ReadTheDocs.org
Main reasons: 
* search engine
* exports (PDF, HTML, ePub). For example, [PDF export](https://media.readthedocs.org/pdf/wallabag/latest/wallabag.pdf)
* multi versions (based on git repo)
* multi languages
* popularity of ReadTheDocs

You can already have a preview here: http://wallabag.readthedocs.org/en/latest/

Todo: 
- [x] ReadTheDocs configuration
- [ ] write documentation for wallabag v2 in english
- [ ] write documentation for wallabag v2 in french

By the way, @CouscousPHP is a great tool, good job @mnapoli :+1: 
We will use Couscous till the end of the year at least.

### CODE REVIEW

**Comment by mnapoli** [comment]
:+1: Couscous is far from supporting those features ;) Thanks for the feedback!

**Comment by araujo0205** [comment]
I want to help to make documentation in Portuguese-br.

**Comment by nicosomb** [comment]
Hello.

Thx for your help.
please have a look to the wallabag/wallabag repository. You have to copy the `docs/en` folder for your language.

**Comment by araujo0205** [comment]
Ok. I Will. When i finish the translation i like to help in another things.

Enviado pelo meu Windows Phone
________________________________
De: Nicolas Lœuillet<mailto:notifications@github.com>
Enviada em: ‎19/‎01/‎2016 03:42
Para: wallabag/documentation<mailto:documentation@noreply.github.com>
Cc: araujo0205<mailto:david.a.souza@outlook.com.br>
Assunto: Re: [documentation] [WIP] Migration to ReadTheDocs (#90)

Hello.

Thx for your help.
please have a look to the wallabag/wallabag repository. You have to copy the `docs/en` folder for your language.

---

**Comment by nicosomb** [comment]
:+1: 
I close this PR, because all the documentation is in https://github.com/wallabag/wallabag repository now.

**Pull request closed without merging**
